name: Fetch M3U8 From EmbedNow

on:
  workflow_dispatch:

jobs:
  grab-m3u8:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Google Chrome Stable
      run: |
        wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt-get install -y ./google-chrome-stable_current_amd64.deb

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Install Python & Playwright
      run: |
        pip install playwright
        python -m playwright install-deps

    - name: Start virtual display
      run: |
        export DISPLAY=:99
        Xvfb :99 -ac -screen 0 1280x720x16 &
        sleep 2

    - name: Run Python
      env:
        DISPLAY: ":99"
      run: python3 TEST1.py

    - name: Upload Output
      uses: actions/upload-artifact@v4
      with:
        name: map7
        path: map7.json
