name: Fetch M3U8 From EmbedNow

on:
  workflow_dispatch:   # bisa run manual

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install Playwright + dependencies
      run: |
        pip install playwright
        python -m playwright install-deps
        python -m playwright install chromium

    - name: Run script (grab m3u8)
      env:
        GITHUB_ACTIONS: "true"
      run: |
        python3 TEST1.py

    - name: Upload map7.json as artifact
      uses: actions/upload-artifact@v4
      with:
        name: map7
        path: map7.json
